kafka.bootstrap.servers=${KAFKA_BROKER:kafka:29092}
kafka.schema.registry.url=${SCHEMA_REGISTRY_URL:http://schema-registry:8081}
kafka.application.id=ripple-detector
kafka.input.topic=service-alerts
kafka.output.topic=ripple-alerts
